// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAEdwNUIMP58-xyr0A4oCzlLs--Mzkx2Mg",
      authDomain: "granth-flutter.firebaseapp.com",
      databaseURL: "https://granth-flutter.firebaseio.com",
      projectId: "granth-flutter",
      storageBucket: "granth-flutter.appspot.com",
      messagingSenderId: "715681207911",
      appId: "1:715681207911:web:f8b107636bbd54d43866c2",
      measurementId: "G-91PL2SQP7D");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyB3Xg_gs8rN-Dc6HNMe7MBentgG9tD0DW8",
      authDomain: "granth-flutter.firebaseapp.com",
      databaseURL: "https://granth-flutter.firebaseio.com",
      projectId: "granth-flutter",
      storageBucket: "granth-flutter.appspot.com",
      messagingSenderId: "715681207911",
      appId: "1:715681207911:android:99c11e6a6e3b87b93866c2",
      measurementId: "G-91PL2SQP7D");
}
